export type BusinessSector = {
  label: string;
  terms: readonly string[];
  excludes: readonly string[];
  weakTerms?: readonly string[];
};

export const businessSectors: readonly BusinessSector[] = [
  {
    label: "Alimentos y alimentación",
    terms: [
      "alimento",
      "alimentacion",
      "comida",
      "catering",
      "comedor",
      "restaurante",
      "abarrote",
      "viveres",
      "cocina",
      "fruta",
      "verdura",
      "refrigerio",
    ],
    excludes: [
      "alimentacion ininterrumpida",
      "sistema de alimentacion",
      "fuente de alimentacion",
      "alimentacion electrica",
      "ups",
      "alimento para animales",
      "alimento animal",
      "analisis microbiologico",
    ],
  },
  {
    label: "Seguridad electrónica y vigilancia",
    terms: [
      "seguridad",
      "camara",
      "videovigilancia",
      "alarma",
      "monitoreo",
      "vigilancia",
      "control de acceso",
      "cctv",
    ],
    excludes: [
      "seguridad alimentaria",
      "seguridad ocupacional",
      "seguridad social",
      "seguridad de la informacion",
      "ciberseguridad",
    ],
  },
  {
    label: "Climatización y refrigeración",
    terms: [
      "aire acondicionado",
      "aires acondicionados",
      "climatizacion",
      "refrigeracion",
      "ventilacion",
      "hvac",
      "camara de frio",
    ],
    excludes: [],
  },
  {
    label: "Limpieza e higiene",
    terms: [
      "limpieza",
      "aseo",
      "desinfeccion",
      "higiene",
      "sanitizacion",
      "detergente",
      "jabon",
      "papel higienico",
      "residuos",
    ],
    excludes: ["limpieza de terreno", "limpieza de lote", "limpieza de cauce"],
  },
  {
    label: "Tecnología y telecomunicaciones",
    terms: [
      "computadora",
      "computo",
      "tecnologia",
      "software",
      "informatica",
      "servidor",
      "licencia",
      "impresora",
      "telecomunicacion",
      "internet",
      "fibra optica",
      "ciberseguridad",
      "redes",
    ],
    excludes: ["red pluvial", "red vial", "red de agua", "red electrica"],
  },
  {
    label: "Construcción y obra civil",
    terms: [
      "construccion",
      "obra civil",
      "obra vial",
      "infraestructura",
      "remodelacion",
      "edificacion",
      "asfalto",
      "concreto",
      "carretera",
      "acera",
      "puente",
    ],
    excludes: ["construccion de software", "construccion de capacidades"],
  },
  {
    label: "Oficina y mobiliario",
    terms: [
      "mobiliario",
      "mueble",
      "escritorio",
      "silla",
      "archivo",
      "suministros de oficina",
      "papeleria",
      "papel",
      "toner",
      "cartucho",
    ],
    excludes: ["papel higienico", "papel para laboratorio"],
  },
  {
    label: "Salud, equipo médico y laboratorio",
    terms: [
      "equipo medico",
      "insumo medico",
      "medicamento",
      "farmaceutico",
      "reactivo",
      "laboratorio",
      "hospitalario",
      "odontologia",
      "clinico",
      "biomedico",
    ],
    excludes: ["laboratorio de computo", "laboratorio de idiomas"],
  },
  {
    label: "Automotriz y repuestos",
    terms: [
      "vehiculo",
      "automotriz",
      "repuesto",
      "llanta",
      "neumatico",
      "lubricante",
      "taller mecanico",
      "motocicleta",
      "motor",
      "frenos",
      "vagoneta",
      "nissan",
      "toyota",
      "isuzu",
      "iveco",
      "hino",
      "mitsubishi",
    ],
    excludes: ["motor electrico", "motor de base de datos"],
    weakTerms: ["repuesto", "motor"],
  },
  {
    label: "Transporte y logística",
    terms: [
      "transporte",
      "logistica",
      "mensajeria",
      "mudanza",
      "acarreo",
      "flete",
      "distribucion",
      "traslado",
    ],
    excludes: ["transporte de datos", "capa de transporte"],
  },
  {
    label: "Capacitación y consultoría",
    terms: [
      "capacitacion",
      "curso",
      "consultoria",
      "asesoria",
      "servicios profesionales",
      "formacion",
      "taller educativo",
      "congreso",
      "certificacion",
    ],
    excludes: ["taller mecanico", "taller automotriz"],
  },
  {
    label: "Impresión, publicidad y comunicación",
    terms: [
      "impresion",
      "imprenta",
      "publicidad",
      "rotulacion",
      "diseno grafico",
      "material promocional",
      "comunicacion",
      "audiovisual",
      "fotografia",
    ],
    excludes: ["impresora", "comunicacion de datos"],
  },
  {
    label: "Hotelería, turismo y eventos",
    terms: [
      "hotel",
      "hospedaje",
      "turismo",
      "evento",
      "salon",
      "alquiler de mobiliario",
      "produccion de eventos",
      "protocolo",
    ],
    excludes: ["salon de clases", "salon comunal construccion"],
  },
  {
    label: "Electricidad y energía",
    terms: [
      "electrico",
      "electricidad",
      "energia",
      "panel solar",
      "fotovoltaico",
      "transformador",
      "generador",
      "cableado",
      "iluminacion",
      "bateria",
    ],
    excludes: ["energia alimentaria", "iluminacion para eventos"],
  },
  {
    label: "Maquinaria, ferretería y herramientas",
    terms: [
      "maquinaria",
      "herramienta",
      "ferreteria",
      "equipo pesado",
      "maquinaria pesada",
      "excavadora",
      "retroexcavadora",
      "soldadura",
      "compresor",
    ],
    excludes: ["herramienta de software", "herramienta informatica"],
  },
  {
    label: "Agricultura, jardinería y ambiente",
    terms: [
      "agricultura",
      "agricola",
      "jardineria",
      "vivero",
      "semilla",
      "planta",
      "reforestacion",
      "ambiental",
      "forestal",
      "poda",
      "riego",
    ],
    excludes: ["planta electrica", "planta de tratamiento"],
  },
  {
    label: "Textiles, uniformes y protección personal",
    terms: [
      "uniforme",
      "textil",
      "ropa",
      "calzado",
      "bordado",
      "equipo de proteccion personal",
      "proteccion personal",
      "casco",
      "chaleco",
      "guante",
    ],
    excludes: ["proteccion de datos", "casco urbano"],
  },
  {
    label: "Contabilidad, auditoría y servicios legales",
    terms: [
      "contabilidad",
      "contable",
      "auditoria",
      "servicio legal",
      "servicios legales",
      "abogado",
      "notarial",
      "financiero",
      "tributario",
    ],
    excludes: ["auditoria de software", "auditoria de sistemas"],
  },
];
